development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: get_schwifty_demo_dev

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: get_schwifty_demo_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: get_schwifty_demo_production
