# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc2fdf7738d61bcc34074de0cd7cf206e951651a661752f08ac9279b8a22b2ac5dea1b6dac3626e5c54eefe9e8d8c0154ccd93484a84eb2a9bab4027fd45f661

test:
  secret_key_base: 3012c924a5f67fa8959859dba2046b204e170325520e9c4b320320dfc1a3863243fe80d4cb7fbd956527ff1b26a3eab81b4a0478f484e19ba483cb14916f2652

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
